{
 "title": "Lab 9",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Quality for requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_max{outcome=\"CLIENT_ERROR\"}[$__interval])"
    },
    {
     "expr": "rate(http_server_requests_seconds_max{outcome=\"SUCCESS\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Performance for requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "gallery_get_time_seconds_max{}" }
   ]
  },
  {
   "title": "Availability for requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "container_last_seen{image=\"mongo:5.0.2\"}"
    }
   ]
  }
 ]
}